version: '3.6'

services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: SrirangaDB
      POSTGRES_DB: PsychometricTest

  graphql-engine:
    image: hasura/graphql-engine:v2.46.0
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:SrirangaDB@postgres:5432/PsychometricTest
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: Civ22jHTO5XTnqkzcE4yiF3Bds0BezO2GDEEaGwxHwSGuitkhSZQmKUfROdBqdkX
      HASURA_GRAPHQL_CORS_DOMAIN: "*"
volumes:
  db_data:
